module(
    name = "slow_compile_demo",
    version = "0.1.0",
)


bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "rules_shell", version = "0.8.0")

bazel_dep(name = "rules_rust", version = "0.71.3")
rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = ["1.90.0"],
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")


bazel_dep(name = "rules_python", version = "2.2.0")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(python_version = "3.12")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pypi",
    python_version = "3.12",
    requirements_lock = "//src-verification/hardware:requirements_lock.txt",
)
use_repo(pip, "pypi")


http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
bazel_dep(name = "rules_foreign_cc", version = "0.15.1")

http_archive(
    name = "verilator_src",
    urls = ["https://github.com/verilator/verilator/archive/refs/tags/v5.034.tar.gz"],
    strip_prefix = "verilator-5.034",
    integrity = "sha256-AC2pjjFspu7kBAf13rfXxDoHiIR9OckNTTHdu8AwIOg=",
    patch_cmds = ["autoconf"],
    build_file_content = """
filegroup(
    name = "all_srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
""",
)