"dhcp_reservations":
- "ip": "10.50.0.1"
  "mac": "02:EE:EE:EE:00:01"
  "name": "host-0-1"
- "ip": "10.50.0.2"
  "mac": "02:EE:EE:EE:00:02"
  "name": "host-0-2"
- "ip": "10.50.0.3"
  "mac": "02:EE:EE:EE:00:03"
  "name": "host-0-3"
- "ip": "10.50.0.4"
  "mac": "02:EE:EE:EE:00:04"
  "name": "host-0-4"
- "ip": "10.50.0.5"
  "mac": "02:EE:EE:EE:00:05"
  "name": "host-0-5"
- "ip": "10.50.0.6"
  "mac": "02:EE:EE:EE:00:06"
  "name": "host-0-6"
- "ip": "10.50.0.7"
  "mac": "02:EE:EE:EE:00:07"
  "name": "host-0-7"
- "ip": "10.50.0.8"
  "mac": "02:EE:EE:EE:00:08"
  "name": "host-0-8"
