[rbe_master]
rbe-worker-1 ansible_host=10.50.0.1 ansible_user=debian ansible_password=debian ansible_become_password=debian

[rbe_workers]
rbe-worker-2 ansible_host=10.50.0.2 ansible_user=debian ansible_password=debian ansible_become_password=debian
rbe-worker-3 ansible_host=10.50.0.3 ansible_user=debian ansible_password=debian ansible_become_password=debian
rbe-worker-4 ansible_host=10.50.0.4 ansible_user=debian ansible_password=debian ansible_become_password=debian
rbe-worker-5 ansible_host=10.50.0.5 ansible_user=debian ansible_password=debian ansible_become_password=debian
rbe-worker-6 ansible_host=10.50.0.6 ansible_user=debian ansible_password=debian ansible_become_password=debian
rbe-worker-7 ansible_host=10.50.0.7 ansible_user=debian ansible_password=debian ansible_become_password=debian
rbe-worker-8 ansible_host=10.50.0.8 ansible_user=debian ansible_password=debian ansible_become_password=debian
rbe-worker-9 ansible_host=10.50.0.9 ansible_user=debian ansible_password=debian ansible_become_password=debian
