load("//src-verification-bazel:hardware-rules.bzl", "verilator_transpile")

filegroup(
    name = "risc_v_deps",
    srcs = glob(["*.sv"]),
    visibility = ["//src-verification/hardware:__pkg__"],
)


verilator_transpile(
    name = "alu",
    srcs = ["alu.sv"],
    top_module = "alu",
    verilator_flags = ["--trace", "-Wno-CASEINCOMPLETE", "--sandbox_debug"],
)