load("//src-verification/hardware:hardware-rules.bzl", "verilator_transpile", "cocotb_module_test")
load("@rules_python//python:defs.bzl", "py_test")
load("@rules_foreign_cc//foreign_cc:defs.bzl", "make")

filegroup(
    name = "risc_v_deps",
    srcs = glob(["*.sv"]),
    visibility = ["//src-verification/hardware:__pkg__"],
)




py_test(
    name = "alu_test",
    srcs = ["alu.py"],
    main = "alu.py",
    deps = [
        "@pypi//cocotb",
        "@pypi//pytest",
    ],
)

py_test(
    name = "control_unit",
    srcs = ["control_unit.py"],
    main = "control_unit.py",
    deps = [
        "@pypi//cocotb",
        "@pypi//pytest",
    ],
)

cocotb_module_test(
    name = "alu_test_cocotb",
    top_module = "alu",
    srcs = ["alu.sv"],
    test_src = "alu.py",
    test_module = "alu",
    verilator_flags = ["--trace", "-Wno-CASEINCOMPLETE", "--public-flat-rw"],
)

cocotb_module_test(
    name = "control_unit_test_cocotb",
    top_module = "control_unit",
    srcs = ["control_unit.sv"],
    test_src = "control_unit.py",
    test_module = "control_unit",
    verilator_flags = ["--trace", "-Wno-CASEINCOMPLETE", "--public-flat-rw"],
)

verilator_transpile(
    name = "alu",
    srcs = ["alu.sv"],
    top_module = "alu",
    verilator_flags = [
        "--trace",
        "-Wno-CASEINCOMPLETE",
        "--public-flat-rw",
    ],
)

filegroup(
    name = "alu_obj_dir_files",
    srcs = [":alu"],
)


filegroup(
    name = "cocotb_vpi_verilator_so",
    srcs = ["@pypi//cocotb:extracted_whl_files"],  # then narrow — see note
)

make(
    name = "alu_bin",
    lib_source = ":alu_obj_dir_files",
    deps = ["//third_party/verilator:verilator_build"],
    env = {
        "CCACHE_DISABLE": "1",
    },
    targets = [
        "-C alu_obj_dir -f Vtop.mk VERILATOR_ROOT=$$EXT_BUILD_DEPS$$/verilator_build/share/verilator LDFLAGS=-Wl,-rpath,\\$$ORIGIN LDLIBS=-L.\\ -l:libcocotbvpi_verilator.so\\ -l:libgpi.so\\ -l:libgpilog.so",
    ],
    postfix_script = "mkdir -p $$INSTALLDIR/bin && cp alu_obj_dir/Vtop $$INSTALLDIR/bin/Vtop",
    out_binaries = ["Vtop"],
    visibility = ["//visibility:public"],
)