load("//src-verification-bazel:hardware-rules.bzl", "verilator_transpile")
load("@rules_python//python:defs.bzl", "py_test")

filegroup(
    name = "risc_v_deps",
    srcs = glob(["*.sv"]),
    visibility = ["//src-verification/hardware:__pkg__"],
)


verilator_transpile(
    name = "alu",
    srcs = ["alu.sv"],
    top_module = "alu",
    verilator_flags = ["--trace", "-Wno-CASEINCOMPLETE"],
)




py_test(
    name = "alu_test",
    srcs = ["alu.py"],
    main = "alu.py",
    deps = [
        "@pypi//cocotb",
        "@pypi//pytest",
    ],
)