load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_test")

N = 10  # how many binaries to generate

[
    rust_binary(
        name = "slow_bin_1_{}".format(i),
        srcs = ["main.rs"],
        edition = "2021",
    )
    for i in range(N)
]


rust_test(
    name = "slow_bin_test",
    srcs = ["main.rs"],
    edition = "2021",
)
