load("//src-verification-bazel:hardware-rules.bzl", "verilator_transpile")
# //src-verification-bazel/hardware-rules.bzl


verilator_transpile(
    name = "risc_v",
    srcs = ["risc_v.sv"],
    deps = ["//src-verification/hardware/subModules:risc_v_deps",],
    top_module = "risc_v",
    verilator_flags = ["--trace", "-Wno-CASEINCOMPLETE"],
)